name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd client
        npm install --legacy-peer-deps

    - name: Build the app
      run: |
        cd client
        npm run build

    - name: Deploy to GitHub Pages
      run: |
        cd client
        npm install gh-pages --save-dev
        npm run deploy